AUDIO_INPUT: Instructors
AUDIO_INPUT_BRCD: BroadcasterMic
AUDIO_INPUTS:
    - Instructors
    - BroadcasterMic

NOTES: Notes
GALLERY: ZoomGalleryCapture
SCENES_WITH_RESIZEABLE_GALLERY: ["Screenshare", "ScreenshareCrop", "ScreenshareLandscape", "BroadcasterScreen", "Notes"]
#SCENES: ["Title", "Gallery", ...SCENES_WITH_RESIZEABLE_GALLERY, "Empty"]
SCENES_SAFE: ["Title", "Notes", "Empty"] # Has no instructor screens
# Scenes which have a remote screenshare from Zoom
SCENES_REMOTE: ["Screenshare", "ScreenshareCrop", "ScreenshareLandscape"]


SCENES:
    Title:
        name: Title
        description: Title screen with logo
    Gallery:
        name: Gallery
        description: All instructors gallery
    Screenshare:
        name: SS Portrait
        description: Screenshare, normal portrait mode.\nUsed when the instructor can share a portion of the screen with the right 840x1080 aspect ratio.
    ScreenshareCrop:
        name: SS Crop
        description: Screenshare, landscape share but crop portrait out of the left 840 pixels.\nUsed when instructors can\'t share a portion of the screen, but share a full screen and we pull an 840x1080 aspect ratio chuck out of the left side of it.
    ScreenshareLandscape:
        name: SS Landscape
        description: Screenshare, actual full landscape mode shrunk into portrait mode.\nUsed when an instructor actually is sharing landscape and you want black bars at the top/bottom to make it fit.
    BroadcasterScreen:
        name: BcdScr
        description: Broadcaster local screen (only broadcaster may select)
    Notes:
        name: Notes
        description: Notes, as screenshared from the broadcaster computer
    Empty:
        name: Empty
        description: Empty black screen



SOUNDS:
    low: '311.wav'
    high: '349.wav'
    alert-high: '622.wav'
    alert-medium: '440.wav'
    alert-low: '261.wav'
INDICATORS:
    indicator-warning: 'red'
    indicator-caution: 'yellow'
    indicator-time: 'yellow'
    indicator-notes: 'cyan'
    indicator-question: 'cyan'
    indicator-chat: 'cyan'
    indicator-slower: 'yellow'
    indicator-faster: 'yellow'


PLAYBACK_INPUT: CRaudio
PLAYBACK_FILES:
    short:
        filename: '/home/rkdarst/git/coderefinery-artwork/audiologo/CR_LOGO_sound_short.mp3'
        tooltip: 'Short audio for coming back from breaks, 0:03 duration'
    long:
        filename: '/home/rkdarst/git/coderefinery-artwork/audiologo/CR_LOGO_Jingle_long.mp3'
        tooltip: 'Long theme song for starting/ending day, 1:23 duration'



GALLERY_CROP_FACTORS:
    0:    {'cropTop':  0, 'cropBottom':  0, 'cropLeft':  0, 'cropRight':  0, }
    1:    {'cropTop':  0, 'cropBottom':  0, 'cropLeft': 59, 'cropRight': 59, }
    2:    {'cropTop': 90, 'cropBottom':  0, 'cropLeft': 12, 'cropRight': 12, }  # checked
    3:    {'cropTop':  4, 'cropBottom':  0, 'cropLeft': 60, 'cropRight': 60, }  # checked
    5:    {'cropTop': 50, 'cropBottom':  0, 'cropLeft': 11, 'cropRight': 11, }  # checked

SCREENSHARE_SIZES:
   - "840x1080"
   - "1920x1080"
   - "1920x1200"
   - "1680x1080"
   - "3840x1080"
