AUDIO_INPUT: Instructors
AUDIO_INPUT_BRCD: BroadcasterMic
AUDIO_INPUTS:
    - Instructors
    - BroadcasterMic

NOTES: Notes
GALLERY: ZoomGalleryCapture
GALLERYTOP: ZoomGalleryTopCapture
SCENES_WITH_RESIZEABLE_GALLERY: ["Screenshare", "ScreenshareCrop", "ScreenshareLandscape", "BroadcasterScreen", "Notes"]
#SCENES: ["Title", "Gallery", ...SCENES_WITH_RESIZEABLE_GALLERY, "Empty"]
SCENES_SAFE: ["Title", "Notes", "Empty"] # Has no instructor screens
# Scenes which have a remote screenshare from Zoom
SCENES_REMOTE: ["Screenshare", "ScreenshareCrop", "ScreenshareLandscape"]


SCENES:
    Title:
        name: Title
        description: Title screen with logo
    Gallery:
        name: Gallery
        description: All instructors gallery
    GalleryTop:
        name: GalleryTop
        description: All instructors gallery in top mode
    Screenshare:
        name: SS Portrait
        description: Screenshare, normal portrait mode.\nUsed when the instructor can share a portion of the screen with the right 840x1080 aspect ratio.
    ScreenshareCrop:
        name: SS Crop
        description: Screenshare, landscape share but crop portrait out of the left 840 pixels.\nUsed when instructors can\'t share a portion of the screen, but share a full screen and we pull an 840x1080 aspect ratio chuck out of the left side of it.
    ScreenshareLandscape:
        name: SS Landscape
        description: Screenshare, actual full landscape mode shrunk into portrait mode.\nUsed when an instructor actually is sharing landscape and you want black bars at the top/bottom to make it fit.
    BroadcasterScreen:
        name: BcdScr
        description: Broadcaster local screen (only broadcaster may select)
    Notes:
        name: Notes
        description: Notes, as screenshared from the broadcaster computer
    Empty:
        name: Empty
        description: Empty black screen



SOUNDS:
    low: '311.wav'
    high: '349.wav'
    alert-high: '622.wav'
    alert-medium: '440.wav'
    alert-low: '261.wav'
INDICATORS:
    warning:  {color: 'red',    sound: 'alert-high',   tooltip: "Generalized 'something urgent has come up'.  Focus on figuring out what that is.", blink: 500}
    caution:  {color: 'yellow', sound: 'alert-medium', tooltip: "Generalized 'something to look at' has come up.  Look when you have time."}
    time:     {color: 'yellow', sound: 'alert-medium', tooltip: "Take a look at the clock."}
    notes:    {color: 'cyan',   sound: 'alert-low',    tooltip: "Check the notes: something has come up."}
    question: {color: 'cyan',   sound: 'alert-low',    tooltip: "Your co-teacher has a question.  Give them time to speak or ask their thoughts."}
    chat:     {color: 'cyan',   sound: 'alert-low',    tooltip: "Check the Zulip chat: something has come up"}
    slower:   {color: 'yellow', sound: 'alert-medium', tooltip: "Try to speak at a slower pace"}
    faster:   {color: 'yellow', sound: 'alert-medium', tooltip: "Try to speak at a faster pace"}


PLAYBACK_INPUT: CRaudio
PLAYBACK_FILES:
    short:
        filename: '/home/rkdarst/git/coderefinery-artwork/audiologo/CR_LOGO_sound_short.mp3'
        tooltip: 'Short audio for coming back from breaks, 0:03 duration'
    long:
        filename: '/home/rkdarst/git/coderefinery-artwork/audiologo/CR_LOGO_Jingle_long.mp3'
        tooltip: 'Long theme song for starting/ending day, 1:23 duration'


# Old crop factors
#GALLERY_CROP_FACTORS:
#    0:    {'cropTop':  0, 'cropBottom':  0, 'cropLeft':  0, 'cropRight':  0, }
#    1:    {'cropTop':  0, 'cropBottom':  0, 'cropLeft': 59, 'cropRight': 59, }
#    2:    {'cropTop': 90, 'cropBottom':  0, 'cropLeft': 12, 'cropRight': 12, }  # checked
#    3:    {'cropTop':  4, 'cropBottom':  0, 'cropLeft': 60, 'cropRight': 60, }  # checked
#    5:    {'cropTop': 50, 'cropBottom':  0, 'cropLeft': 11, 'cropRight': 11, }  # checked

# Zoom Classic
# For a 1190 x 750 windows
# top corp is 40 and bottom is 58
# top = top-40 + 3
# left/right = side + 2
# bottom = 750 - bottom - 58
#GALLERY_CROP_FACTORS:
#    0:    {'cropTop':   0, 'cropBottom':   0, 'cropLeft':  0, 'cropRight':  0, }
#    1:    {'cropTop':   8, 'cropBottom':   2, 'cropLeft': 20, 'cropRight': 20, } # 45, 20, 690, checked
#    2:    {'cropTop': 174, 'cropBottom': 166, 'cropLeft': 25, 'cropRight': 25, } # 211, 23, 526, calculated
#    3:    {'cropTop':  10, 'cropBottom':   4, 'cropLeft': 28, 'cropRight': 28, } # 47, 26, 688, calculated
#    5:    {'cropTop': 117, 'cropBottom': 111, 'cropLeft': 24, 'cropRight': 24, } # 154, 22, 581, calculated

# Zoom Workplace (window name: Meeting)
# 1190 x 804
GALLERY_CROP_FACTORS:
    0:    {'cropTop':  95, 'cropBottom':  72, 'cropLeft':  2, 'cropRight':  2, }  # checked
    1:    {'cropTop': 110, 'cropBottom': 130, 'cropLeft': 94, 'cropRight': 94, }  # checked
    2:    {'cropTop': 230, 'cropBottom': 251, 'cropLeft': 20, 'cropRight': 20, }  # checked
    3:    {'cropTop': 110, 'cropBottom': 129, 'cropLeft': 94, 'cropRight': 94, }  # checked
    5:    {'cropTop': 175, 'cropBottom': 190, 'cropLeft': 21, 'cropRight': 21, }  # checked
    7:    {'cropTop': 110, 'cropBottom': 120, 'cropLeft': 92, 'cropRight': 92, }  # checked

# Zoom Workplace Crop factors in "top gallery" mode.  Does not include
# the height of the screenshare, which gets added to these values.
# 2 + 272 + 200×n + 96 + 272 + 2
TOPGALLERY_CROP_FACTORS:
    0: {cropTop: 70, cropBottom: 76, cropLeft: 2, cropRight: 2}
    1: {cropTop: 70, cropBottom: 74, cropLeft: 100, cropRight: 100}     # L/R crop factors aren't used
    2: {cropTop: 70, cropBottom: 74, cropLeft: 110, cropRight: 110}
    3: {cropTop: 70, cropBottom: 74, cropLeft: 120, cropRight: 120}
    5: {cropTop: 70, cropBottom: 74, cropLeft: 130, cropRight: 130}


SCREENSHARE_SIZES:
   - "840x1080"
   - "1920x1080"
   - "1920x1200"
   - "1680x1080"
   - "3840x1080"

# Crop factors to get to the screenshare in "top gallery" mode.
# This is added to the screenshare WxH to get the size to which
# the window should be set.
SCREENSHARE_TOPGALLERY_BORDER: {top: 195, bottom: 74, left: 2, right: 2, }

SS_RESOLUTION:
  # Zoom classic.  Has no extra border
  zoom:
    command: "xdotool search --onlyvisible --name '^Zoom$' windowsize WIDTH HEIGHT;"
    border_pixels: [0, 0]
  # Zoom Workplace second window: top=65, left=2, right=2, bottom=2
  zoomw:
    command: "xdotool search --onlyvisible --name '^Zoom Workplace$' windowsize WIDTH HEIGHT;"
    border_pixels: [65, 0] # prev [67, 4]  # Crop set in OBS scene-item properties
    command_resetmainwindow: "xdotool search --onlyvisible --name '^Meeting$' windowsize 1190 804;"
    mainwindow_forcesize: [1190, 804]
  zoomw-top:
    command: "xdotool search --onlyvisible --name '^Meeting$' windowsize WIDTH HEIGHT;"
    border_pixels: [0, 0]
